services:
  - type: web
    name: coffeegpt-telegram
    env: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
